### ISSUE TITLE
[Enhancement] Add Support for Parametric Polymorphism

### ISSUE THREAD

**Issue by keyan-m** [Hyperion-BT/helios#71] opened 2023-03-20 17:51 UTC
Supporting polymorphism allows implementation of more abstract functions.

An example use-case written in Plutus:
```hs
helper :: [TxInInfo] -> [TxInInfo] -> (TxOut -> TxOut -> a) -> a
helper inputs references handler = ...
```
In this example, this helper function can expect specific patterns for the given inputs and reference inputs, while allowing various behaviors through it's `handler` argument.

**Comment by keyan-m** [comment] 2023-03-20 19:50
At the risk of stating the obvious, this shouldn't open the door to dynamic typing. That is, if the return type is inferred as anything more concrete than the claimed polymorphism, the compiler should fail with a type error.

**Comment by christianschmitz** [comment] 2023-03-20 20:26
> At the risk of stating the obvious, this shouldn't open the door to dynamic typing. That is, if the return type is inferred as anything more concrete than the claimed polymorphism, the compiler should fail with a type error.

In the above example `a` is constrained by `MyTypeConstraint`, and everything that is of type `a` has to be exactly of type `a` (no up or down casting). When calling the function the concrete type will have to be specified:

```
result: ConcreteType = helper[ConcreteType](...)
```

In most cases `ConcreteType` will be inferable though. @keyan-m are you ok with that?

**Comment by christianschmitz** [comment] 2023-03-21 16:44
@keyan-m It would be the cleanest way to support mutual recursion. Due to the limitations of Plutus-Core any kind of recursion requires passing functions as arguments.

Also: the most basic type-class can have `to_data` and `from_data` methods, which can be used to convert to/from primitive types much more cleanly (currently a lot of IR code is generated twice, once for bool and once for `data` (and `int` is kept as `data`).

**Comment by christianschmitz** [comment] 2023-05-16 08:34
The implementation has been merged into the dev branch.

If you have time, please help me test this.

Some examples:

A parametric function:
```
 func deserialize[A](a: Data) -> A {
      A::from_data(a)
    }
    
```

A parametric function a non-default typeclass:
```
 func get_value[V: Valuable](v: V) -> Value {
   v.value
 }
```

A parametric enum:
```
  testing merkle_trees

  enum BinaryTree[A] {
    // represents no value (null object pattern)
    Empty
  
    Leaf { hash: A }
  
    Node {
      hash: A
      left: BinaryTree[A]
      right: BinaryeTree[A]
    }
  }
  
  func main() -> Bool {
      a = BinaryTree[ByteArray]::Empty;
      b = BinaryTree[ByteArray]::Leaf{#abcd};
      c = BinaryTree[ByteArray]::Node{hash: #1234, left: a, right: b};
      (c.left == a).trace("left equal to a: ")
  }
```

A parametric struct with a parametric method:
```
testing type_parameters
  
  struct Pair[A, B] {
    a: A
    b: B

    func serialize_custom(self) -> ByteArray {
      self.a.serialize() + self.b.serialize()
    }

    func serialize_2[C](self, other: C) -> ByteArray {
      self.serialize_custom() + other.serialize()
    }
  }

  func main() -> Bool {
    p = Pair[Int, Int]{10, 11};

    p.serialize_custom().length < p.serialize_2(true).length
  }
```

Builtin typeclasses (WiP):
* `Any`: matches everything, including functions (used in the `fold` methods)
* default (empty): matches everything except function types
* `Valuable`: anything with the `value: Value` getter (because getters can be defined by a user, this only matches `TxInput`, `TxOutput` and `Value` itself)

Notes:
* only enum, struct, and func-statements can be parametric. Expressions are never parametric
* user-defined typeclasses aren't yet possible

**Comment by christianschmitz** [comment] 2023-05-22 17:19
`dev` branch has been merged into `main` -> v0.14.0

@keyan-m feel free to close this issue once you get a chance to review the implementation

**Comment by keyan-m** [comment] 2023-05-22 18:15
Thank you, we will hopefully get to test it in 2-3 weeks.

**Comment by ritterbush** [comment] 2023-06-09 17:32
Everything is working so far, except it looks like tupled (or multi-valued) generics is giving an error. We were not sure if this was intended, since it encourages the use of using record/struct data types! Thanks for your implementation of generics. For our use case, it seems to be working well.

**Comment by christianschmitz** [comment] 2023-06-27 22:18
@ritterbush yes, that was intentional

Will close this issue, as it's been a while since I've seen any bugs related to this

**Closed by christianschmitz** 2023-06-27 22:18 UTC
